plugins {
	id("com.github.johnrengelman.shadow").version("8.1.1").apply(false)
	id("architectury-plugin").version("3.4-SNAPSHOT")
	id("dev.architectury.loom").version("1.10-SNAPSHOT").apply(false)
	id('xyz.wagyourtail.jvmdowngrader').version("${jvmdowngrader_version}")
}

architectury {
	minecraft = minecraft_version
}

def sysProps = System.getProperties()
println "Java: ${ -> sysProps['java.version']} | JVM: ${ -> sysProps['java.vm.version']} | Vendor: ${ -> sysProps['java.vendor']} | Architecture: ${ -> sysProps['os.arch']}"

subprojects {
	apply plugin: "com.github.johnrengelman.shadow"
	apply plugin: "dev.architectury.loom"
	apply plugin: 'xyz.wagyourtail.jvmdowngrader'

	configurations {
		shade
		implementation.extendsFrom(shade)
	}

	shadowJar {
		configurations = [project.configurations.shade]

		relocate("net.neoforged.srgutils", "dev.latvian.mods.rhino.shaded.srgutils")

		archiveClassifier.set("shadow")
	}

	remapJar {
		setInput(shadeDowngradedApi.archiveFile)
		dependsOn(downgradeJar)

		archiveClassifier.set(project.name)
	}

	assemble.dependsOn(shadeDowngradedApi)

	loom {
		silentMojangMappingsLicense()
	}

	dependencies {
		minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
		mappings loom.layered() {
			officialMojangMappings()
			parchment("org.parchmentmc.data:parchment-${rootProject.minecraft_version}:2021.10.10")
		}

		// https://mvnrepository.com/artifact/net.neoforged/srgutils
		shade('net.neoforged:srgutils:1.0.9')

		//lombok, see https://projectlombok.org/setup/gradle
		compileOnly("org.projectlombok:lombok:$lombok_version")
		annotationProcessor("org.projectlombok:lombok:$lombok_version")
		testCompileOnly("org.projectlombok:lombok:$lombok_version")
		testAnnotationProcessor("org.projectlombok:lombok:$lombok_version")

		// Unit Testing
		testImplementation("org.junit.jupiter:junit-jupiter-api:$junit_version")
		testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junit_version")
	}

	test {
//		useJUnitPlatform()
	}
}

allprojects {
	apply plugin: "java"
	apply plugin: "architectury-plugin"
	apply plugin: "maven-publish"

	def ENV = System.getenv()
	version = mod_version //	version = "${mod_version}-build.${ENV.GITHUB_RUN_NUMBER ?: 9999}"
	group = project.mod_package
	archivesBaseName = project.mod_name

	tasks.withType(JavaCompile.class) {
		sourceCompatibility = 21
		options.encoding = "UTF-8"
		options.compilerArgs << "-parameters"
	}

	repositories {
		mavenCentral()

		maven {
			url "https://maven.architectury.dev/"
		}

		maven {
			url "https://www.cursemaven.com"
			content {
				includeGroup "curse.maven"
			}
		}

		maven {
			url "https://maven.saps.dev/minecraft"
			content {
				includeGroup "dev.latvian.mods"
				includeGroup "dev.ftb.mods"
			}
		}

		maven {
			url = "https://maven.parchmentmc.net/"
			content {
				includeGroup "org.parchmentmc.data"
			}
		}
	}

	java {
		withSourcesJar()
	}
}

task curseforgePublish